-- Add Razorpay payment tracking columns for automation
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS razorpay_payment_id VARCHAR(100);
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS refund_id VARCHAR(100);

-- Document purpose:
-- razorpay_payment_id: Stores the successful payment ID from Razorpay to allow refunds.
-- refund_id: Stores the unique refund ID generated by Razorpay upon successful automated reversal.
